baseURL: https://bordeaux-iut-de-bordeaux.web.deuxfleurs.fr

## LANGUAGE
defaultContentLanguage: fr
defaultContentLanguageInSubdir: false

## CACHE
deployment:
  matchers:
    - pattern: "^.+\\.(woff2|woff|svg|ttf|eot|js|css)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
    - pattern: "^.+\\.(png|jpg|jpeg|gif|webp)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: false
  ## DEUXFLEURS
  targets:
    - name: "staging"
      URL: "s3://bordeaux-iut-de-bordeaux?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage&awssdk=v1"